openapi: 3.0.0
info:
  title: Stock Data API
  description: API for retrieving historical stock data and sending reports via email
  version: 1.0.0
  contact:
    email: info@example.com

servers:
  - url: http://localhost:3000
    description: Local development server

components:
  schemas:
    StockRequest:
      type: object
      required:
        - companySymbol
        - startDate
        - endDate
        - email
      properties:
        companySymbol:
          type: string
          description: Valid NASDAQ company symbol
          example: "AAPL"
        startDate:
          type: string
          format: date
          description: Start date in YYYY-MM-DD format
          example: "2024-01-01"
        endDate:
          type: string
          format: date
          description: End date in YYYY-MM-DD format
          example: "2024-01-31"
        email:
          type: string
          format: email
          description: Email address to receive the stock report
          example: "user@example.com"
    
    StockResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the request
          example: "507f1f77bcf86cd799439011"
        companySymbol:
          type: string
          description: Company symbol used in the request
          example: "AAPL"
        status:
          type: string
          enum: [pending, completed, failed]
          description: Current status of the request
          example: "completed"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the request was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the request was last updated

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Field that caused the error
              message:
                type: string
                description: Specific error message for the field

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/stock-requests:
    post:
      summary: Create a new stock data request
      description: |
        Creates a new request for historical stock data. The system will:
        1. Validate the input parameters
        2. Fetch historical data for the specified date range
        3. Send an email with the data in CSV format
      tags:
        - Stock Requests
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockRequest'
      responses:
        '201':
          description: Request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalidSymbol:
                  value:
                    message: "Validation failed"
                    errors: [
                      {
                        field: "companySymbol",
                        message: "Invalid company symbol"
                      }
                    ]
                invalidDate:
                  value:
                    message: "Validation failed"
                    errors: [
                      {
                        field: "startDate",
                        message: "Start date must be before end date"
                      }
                    ]
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /api/stock-requests/{id}:
    get:
      summary: Get a stock request by ID
      description: Retrieves the details and status of a specific stock request
      tags:
        - Stock Requests
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the stock request
      responses:
        '200':
          description: Request found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockResponse'
        '404':
          description: Request not found
        '401':
          description: Unauthorized

  /api/stock-symbols:
    get:
      summary: Get available stock symbols
      description: Retrieves the list of available NASDAQ stock symbols
      tags:
        - Stock Symbols
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
          description: Optional search term to filter symbols
      responses:
        '200':
          description: List of stock symbols
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    symbol:
                      type: string
                      example: "AAPL"
                    company:
                      type: string
                      example: "Apple Inc."

tags:
  - name: Stock Requests
    description: Endpoints for managing stock data requests
  - name: Stock Symbols
    description: Endpoints for retrieving available stock symbols